Complete test overhaul
marlinprotocol/control-plane pull request #30
Opened 2023-08-03 08:19 UTC by nisarg-soni

- Moved test input to inside tests for better visibility
- Added simulator to test spin up and down times
- Added more detailed checks on spin up and down outcomes
- Improved naming

2023-08-03 12:56 UTC, arnav-deep approved these changes

2023-08-04 07:47 UTC, roshanr95 requested changes
A lot of stuff can be moved inside `#cfg[(test)]` like TestLogger, TestAws, the trait impls, etc. Move anything not strictly required for cp inside it so it's all excluded when tests are not being run.

2023-08-04 08:13 UTC, arnav-deep commented
> A lot of stuff can be moved inside `#cfg[(test)]` like TestLogger, TestAws, the trait impls, etc. Move anything not strictly required for cp inside it so it's all excluded when tests are not being run.

Yeah. I discussed this with @nisarg-soni and I'll raise a PR to this branch for that. Already have made the changes in another branch. Just need to edit a few things.

2023-08-04 09:14 UTC, arnav-deep approved these changes

2023-08-04 09:46 UTC, nisarg-soni commented
> 

Resolved

2023-08-06 07:44 UTC, roshanr95 approved these changes

2023-08-06 07:44 UTC, merged